baseURL = "https://williamgyes.github.io/"
languageCode = "zh-Hans"
theme = "moments"
paginate = 10
paginatePath = '.'

[params]
    title = "Moments Demo"
    signature = "得意淡然，失意泰然。"
    cover = "https://cdn.pixabay.com/photo/2018/03/13/22/53/puzzle-3223941_1280.jpg"

    name = "William Gong"
    avatar = "/img/default_avatar.png"
